name: public
named: {}
views:
  #Content Views
  uesio/web.allinclusiveitem: true
  uesio/web.blog: true
  uesio/web.blogentry: true
  uesio/web.contact: true
  uesio/web.demo: true
  uesio/web.earlyaccess: true
  uesio/web.featurewithicon: true
  uesio/web.footer: true
  uesio/web.home: true
  uesio/web.preview: true
  uesio/web.pricing: true
  uesio/web.pricingcard: true
  uesio/web.privacy: true
  uesio/web.terms: true
  uesio/web.topbar: true
  #Authentification Views
  uesio/web.login: true
  uesio/web.loginarea: true
  uesio/web.changepassword: true
  uesio/web.requestpassword: true
collections:
  uesio/cms.article:
    read: true
    create: false
    edit: false
    delete: false
    modifyall: false
    viewall: false
    fields: {}
  uesio/core.userfile:
    read: true
    create: false
    edit: false
    delete: false
    modifyall: false
    viewall: false
    fields: {}
routes:
  #Content Routes
  uesio/web.blog: true
  uesio/web.blogentry: true
  uesio/web.contact: true
  uesio/web.demo: true
  uesio/web.earlyaccess: true
  uesio/web.home: true
  uesio/web.preview: true
  uesio/web.pricing: true
  uesio/web.privacy: true
  uesio/web.terms: true
  #Authentification Routes
  uesio/web.signup: true
  uesio/web.changepassword: true
  uesio/web.requestpassword: true
  uesio/web.login: true
files:
  uesio/web.aws: true
  uesio/web.aws_marketplace: true
  uesio/web.logo: true
  uesio/web.logowhite_full: true
  uesio/web.linkedin: true
  uesio/web.problem_icon: true
  uesio/web.banner: true
  uesio/web.bg_banner: true
  uesio/web.blocks: true
  uesio/web.solution_icon: true
  uesio/web.arrow_blue: true
  uesio/web.arrow_primary_light: true
  uesio/web.swissmade: true
  uesio/web.youtube: true
bots:
  uesio/web.request: true
  uesio/web.createlogin: true
  uesio/web.forgotpassword: true
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: false
allowallintegrationactions: true
modifyallrecords: false
viewallrecords: false
