name: Main Branch Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and release to prod
    uses: ./.github/workflows/patch_build_and_release.yaml
    with:
      environment: prod
    secrets: inherit
